/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_game_search`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGameSearchError {
    Status400(models::Error),
    Status404(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_items_all_search`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetItemsAllSearchError {
    Status400(models::Error),
    Status404(models::Error),
    UnknownValue(serde_json::Value),
}


/// Search in all names and descriptions of all supported types in the game. For the list of supported types see the endpoint /dofus3/meta/search/types.
pub async fn get_game_search(configuration: &configuration::Configuration, language: &str, game: &str, query: &str, filter_left_square_bracket_search_index_right_square_bracket: Option<Vec<String>>, limit: Option<i32>, fields_left_square_bracket_item_right_square_bracket: Option<Vec<String>>, filter_left_square_bracket_type_name_id_right_square_bracket: Option<Vec<String>>) -> Result<Vec<models::GameSearch>, Error<GetGameSearchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_language = language;
    let p_path_game = game;
    let p_query_query = query;
    let p_query_filter_left_square_bracket_search_index_right_square_bracket = filter_left_square_bracket_search_index_right_square_bracket;
    let p_query_limit = limit;
    let p_query_fields_left_square_bracket_item_right_square_bracket = fields_left_square_bracket_item_right_square_bracket;
    let p_query_filter_left_square_bracket_type_name_id_right_square_bracket = filter_left_square_bracket_type_name_id_right_square_bracket;

    let uri_str = format!("{}/{game}/v1/{language}/search", configuration.base_path, language=crate::apis::urlencode(p_path_language), game=crate::apis::urlencode(p_path_game));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("query", &p_query_query.to_string())]);
    if let Some(ref param_value) = p_query_filter_left_square_bracket_search_index_right_square_bracket {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter[search_index]".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter[search_index]", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields_left_square_bracket_item_right_square_bracket {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields[item]".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields[item]", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_filter_left_square_bracket_type_name_id_right_square_bracket {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter[type.name_id]".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter[type.name_id]", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GameSearch&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::GameSearch&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGameSearchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Search in all names and descriptions of Dofus items (including all subtypes) with a query.
pub async fn get_items_all_search(configuration: &configuration::Configuration, language: &str, game: &str, query: &str, filter_left_square_bracket_min_level_right_square_bracket: Option<i32>, filter_left_square_bracket_max_level_right_square_bracket: Option<i32>, limit: Option<i32>, filter_left_square_bracket_type_name_id_right_square_bracket: Option<Vec<String>>) -> Result<Vec<models::ListItemGeneral>, Error<GetItemsAllSearchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_language = language;
    let p_path_game = game;
    let p_query_query = query;
    let p_query_filter_left_square_bracket_min_level_right_square_bracket = filter_left_square_bracket_min_level_right_square_bracket;
    let p_query_filter_left_square_bracket_max_level_right_square_bracket = filter_left_square_bracket_max_level_right_square_bracket;
    let p_query_limit = limit;
    let p_query_filter_left_square_bracket_type_name_id_right_square_bracket = filter_left_square_bracket_type_name_id_right_square_bracket;

    let uri_str = format!("{}/{game}/v1/{language}/items/search", configuration.base_path, language=crate::apis::urlencode(p_path_language), game=crate::apis::urlencode(p_path_game));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("query", &p_query_query.to_string())]);
    if let Some(ref param_value) = p_query_filter_left_square_bracket_min_level_right_square_bracket {
        req_builder = req_builder.query(&[("filter[min_level]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_left_square_bracket_max_level_right_square_bracket {
        req_builder = req_builder.query(&[("filter[max_level]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter_left_square_bracket_type_name_id_right_square_bracket {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter[type.name_id]".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter[type.name_id]", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ListItemGeneral&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ListItemGeneral&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetItemsAllSearchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

