/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAlmanaxWebhook {
    /// from all available bonuses (ids) from /dofus3/meta/{language}/almanax/bonuses
    #[serde(rename = "bonus_whitelist", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bonus_whitelist: Option<Option<Vec<String>>>,
    /// from all available bonuses (ids) from /dofus3/meta/{language}/almanax/bonuses
    #[serde(rename = "bonus_blacklist", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bonus_blacklist: Option<Option<Vec<String>>>,
    /// Get the available subscriptions with /meta/webhooks/almanax
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<String>,
    #[serde(rename = "format")]
    pub format: Format,
    /// Discord Webhook URL
    #[serde(rename = "callback")]
    pub callback: String,
    #[serde(rename = "daily_settings", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub daily_settings: Option<Option<Box<models::CreateAlmanaxWebhookDailySettings>>>,
    /// If false, it will use common local time formats and weekday translations. If true, the format is YYYY-MM-DD.
    #[serde(rename = "iso_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso_date: Option<Option<bool>>,
    /// Almanax bonus ids mapped to array of mentions.
    #[serde(rename = "mentions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Option<std::collections::HashMap<String, Vec<models::CreateAlmanaxWebhookMentionsValueInner>>>>,
    /// - Daily posts each day, filtering with Black/Whitelist and mentions are applied daily. - Weekly posts the next 7 days (excluding the posting day) once per week at the specified time. With only weekly selected, of all mentions, only prior notices will come through daily. The 7 day preview gets filtered by the Black/Whitelist. - Monthly posts a preview of the next month from first to last date. The post will be on the last day of a month (ignoring day of the week) at the specified time. Mentions and filtering works like weekly. The biggest difference between daily and the other two is that daily always posts the current day while monthly and weekly only show future days. You can always combine the intervals by selecting multiple intervals for one hook or create multiple hooks for the same channel with different settings to get every highly specific combination you want.
    #[serde(rename = "intervals")]
    pub intervals: std::collections::HashSet<Intervals>,
    /// When to post the weekly preview at the specified time.
    #[serde(rename = "weekly_weekday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weekly_weekday: Option<Option<WeeklyWeekday>>,
}

impl CreateAlmanaxWebhook {
    pub fn new(subscriptions: Vec<String>, format: Format, callback: String, intervals: std::collections::HashSet<Intervals>) -> CreateAlmanaxWebhook {
        CreateAlmanaxWebhook {
            bonus_whitelist: None,
            bonus_blacklist: None,
            subscriptions,
            format,
            callback,
            daily_settings: None,
            iso_date: None,
            mentions: None,
            intervals,
            weekly_weekday: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "discord")]
    Discord,
}

impl Default for Format {
    fn default() -> Format {
        Self::Discord
    }
}
/// - Daily posts each day, filtering with Black/Whitelist and mentions are applied daily. - Weekly posts the next 7 days (excluding the posting day) once per week at the specified time. With only weekly selected, of all mentions, only prior notices will come through daily. The 7 day preview gets filtered by the Black/Whitelist. - Monthly posts a preview of the next month from first to last date. The post will be on the last day of a month (ignoring day of the week) at the specified time. Mentions and filtering works like weekly. The biggest difference between daily and the other two is that daily always posts the current day while monthly and weekly only show future days. You can always combine the intervals by selecting multiple intervals for one hook or create multiple hooks for the same channel with different settings to get every highly specific combination you want.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Intervals {
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "monthly")]
    Monthly,
}

impl Default for Intervals {
    fn default() -> Intervals {
        Self::Daily
    }
}
/// When to post the weekly preview at the specified time.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WeeklyWeekday {
    #[serde(rename = "sunday")]
    Sunday,
    #[serde(rename = "monday")]
    Monday,
    #[serde(rename = "tuesday")]
    Tuesday,
    #[serde(rename = "wednesday")]
    Wednesday,
    #[serde(rename = "thursday")]
    Thursday,
    #[serde(rename = "friday")]
    Friday,
    #[serde(rename = "saturday")]
    Saturday,
}

impl Default for WeeklyWeekday {
    fn default() -> WeeklyWeekday {
        Self::Sunday
    }
}

