/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateAlmanaxWebhookMentionsValueInner : Mention
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAlmanaxWebhookMentionsValueInner {
    /// User or role ID directly from Discord. Activate developer mode and right click a user or role to get them.
    #[serde(rename = "discord_id", skip_serializing_if = "Option::is_none")]
    pub discord_id: Option<i32>,
    /// Whether an ID describes a role (true) or user (false). This is needed for formatting the mention command so Discord understands it.
    #[serde(rename = "is_role", skip_serializing_if = "Option::is_none")]
    pub is_role: Option<bool>,
    /// Get a mention days before the bonus comes up. It will post on the specified time. Also works when the interval is not daily.
    #[serde(rename = "ping_days_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ping_days_before: Option<Option<i32>>,
}

impl CreateAlmanaxWebhookMentionsValueInner {
    /// Mention
    pub fn new() -> CreateAlmanaxWebhookMentionsValueInner {
        CreateAlmanaxWebhookMentionsValueInner {
            discord_id: None,
            is_role: None,
            ping_days_before: None,
        }
    }
}

