/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListItem {
    #[serde(rename = "ankama_id", skip_serializing_if = "Option::is_none")]
    pub ankama_id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<models::TranslatedId>>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    #[serde(rename = "image_urls", skip_serializing_if = "Option::is_none")]
    pub image_urls: Option<Box<models::Images>>,
    #[serde(rename = "recipe", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Option<Vec<models::Recipe>>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "conditions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Option<Box<models::ConditionNode>>>,
    #[serde(rename = "effects", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub effects: Option<Option<Vec<models::Effect>>>,
    #[serde(rename = "is_weapon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_weapon: Option<Option<bool>>,
    #[serde(rename = "pods", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pods: Option<Option<i32>>,
    #[serde(rename = "parent_set", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_set: Option<Option<Box<models::TranslatedId>>>,
    #[serde(rename = "critical_hit_probability", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub critical_hit_probability: Option<Option<i32>>,
    #[serde(rename = "critical_hit_bonus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub critical_hit_bonus: Option<Option<i32>>,
    #[serde(rename = "max_cast_per_turn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_cast_per_turn: Option<Option<i32>>,
    #[serde(rename = "ap_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ap_cost: Option<Option<i32>>,
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<Box<models::Range>>,
}

impl ListItem {
    pub fn new() -> ListItem {
        ListItem {
            ankama_id: None,
            name: None,
            r#type: None,
            level: None,
            image_urls: None,
            recipe: None,
            description: None,
            conditions: None,
            effects: None,
            is_weapon: None,
            pods: None,
            parent_set: None,
            critical_hit_probability: None,
            critical_hit_bonus: None,
            max_cast_per_turn: None,
            ap_cost: None,
            range: None,
        }
    }
}

